#!/bin/bash

# Deploy an image on the target. It does it in 2 phases:
#	* copy the image on a SD Card
#	* Extend the rootfs partition
#
#   usage is "deploy_imag.sh -d <DEVICE> -i <IMAGE>" -t <TARGET>

# List of the supported targets (virtual targets not supported)
targets="rpi4_64 de1soc"

function usage()
{
    echo "Usage: $0 -d <DEVICE> -i <IMAGE>"
    echo ""
    echo "Where OPTIONS are:"
    echo "  -d   device name (ex: sdb or mmcblk0 or other...)"
    echo "  -i   Image to copy on the device. The path can be absolute or relative"
    echo "       to the script folder"
    echo "  -t   target "
    echo ""
    echo " Supported targets: $targets"
    echo ""
    echo "  Note: The images generated by 'gen_image.sh' are put in <ROOT>/images/images folder"
    echo ""
    exit 1
}

function check_target()
{
    for i in $targets; do
        if [ "$i" = "$1" ]; then
            # It is a valid target
            return
        fi
    done

    echo "ERROR: target '$1' is not supported. Valid targets are '$targets'"
    exit 1
}

# == Check parameters == #

device=""
image=""

while getopts "d:i:t:" o; do
    case "$o" in

        d)
            device=${OPTARG}
            ;;
        i)
            image=${OPTARG}
            ;;
        t)
            target=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

check_target $target

# Check if all required options are provided
if [ -z "$device" ] || [ -z "$image" ]; then
    echo "Error: All options are not passed."
    usage
fi

# Check for extra arguments
if [ $OPTIND -le $# ]; then
    echo "Error: Extra arguments provided."
    usage
fi

if [ ! -f "$image" ]; then
    echo "Error: File '$image' does not exist."
    exit 1
fi

if [ ! -b "/dev/$device" ]; then
    echo "Error: Device '/dev/$device' does not exist."
    exit 1
fi

# == Copy image on the SD card == #
echo "Copying image to SD card..."
sudo dd if=$image of=/dev/$device bs=1M conv=fsync status=progress

# == Extend ROOTFS partition on the SC Card == #
if [ "$target" == "de1soc" ]; then
    rootfspart=3
else
    rootfspart=2
fi

 # Resize ROOTFS partition
echo "Resizing the ROOTFS partition..."
sudo parted --script "/dev/$device" resizepart $rootfspart 100%

# Resize the filesystem to use the full space (ext4)
if [[ "$device" = *[0-9] ]]; then
    device="${device}p"
fi

sudo e2fsck -f /dev/"$device$rootfspart"
sudo resize2fs /dev/"$device$rootfspart"
