# TCL File Generated by Component Editor 18.1
# Wed Jun 10 15:26:11 CEST 2026
# DO NOT MODIFY


# 
# AXI4Lite "AXI4Lite" v1.0
#  2026.06.10.15:26:11
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AXI4Lite
# 
set_module_property DESCRIPTION ""
set_module_property NAME AXI4Lite
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AXI4Lite
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi4lite_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi4lite_slave.vhd VHDL PATH ../src/axi4lite_slave.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter AXI_DATA_WIDTH INTEGER 32
set_parameter_property AXI_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property AXI_DATA_WIDTH DISPLAY_NAME AXI_DATA_WIDTH
set_parameter_property AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property AXI_DATA_WIDTH UNITS None
set_parameter_property AXI_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter AXI_ADDR_WIDTH INTEGER 12
set_parameter_property AXI_ADDR_WIDTH DEFAULT_VALUE 12
set_parameter_property AXI_ADDR_WIDTH DISPLAY_NAME AXI_ADDR_WIDTH
set_parameter_property AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property AXI_ADDR_WIDTH UNITS None
set_parameter_property AXI_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock clock_sink
set_interface_property altera_axi4lite_slave associatedReset reset_sink
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave axi_araddr_i araddr Input 12
add_interface_port altera_axi4lite_slave axi_arprot_i arprot Input 3
add_interface_port altera_axi4lite_slave axi_arready_o arready Output 1
add_interface_port altera_axi4lite_slave axi_arvalid_i arvalid Input 1
add_interface_port altera_axi4lite_slave axi_awaddr_i awaddr Input 12
add_interface_port altera_axi4lite_slave axi_awprot_i awprot Input 3
add_interface_port altera_axi4lite_slave axi_awready_o awready Output 1
add_interface_port altera_axi4lite_slave axi_awvalid_i awvalid Input 1
add_interface_port altera_axi4lite_slave axi_bready_i bready Input 1
add_interface_port altera_axi4lite_slave axi_bresp_o bresp Output 2
add_interface_port altera_axi4lite_slave axi_rdata_o rdata Output 32
add_interface_port altera_axi4lite_slave axi_bvalid_o bvalid Output 1
add_interface_port altera_axi4lite_slave axi_rready_i rready Input 1
add_interface_port altera_axi4lite_slave axi_rresp_o rresp Output 2
add_interface_port altera_axi4lite_slave axi_rvalid_o rvalid Output 1
add_interface_port altera_axi4lite_slave axi_wdata_i wdata Input 32
add_interface_port altera_axi4lite_slave axi_wready_o wready Output 1
add_interface_port altera_axi4lite_slave axi_wstrb_i wstrb Input 4
add_interface_port altera_axi4lite_slave axi_wvalid_i wvalid Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_i reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end input_reg_data_i input_reg_data_i Input 32
add_interface_port conduit_end input_reg_crcin_i input_reg_crcin_i Input 32
add_interface_port conduit_end input_reg_init_i input_reg_init_i Input 32
add_interface_port conduit_end input_reg_size_i input_reg_size_i Input 32
add_interface_port conduit_end input_reg_xorout_i input_reg_xorout_i Input 32
add_interface_port conduit_end output_reg_crcout_o output_reg_crcout_o Output 32
add_interface_port conduit_end output_reg_status_o output_reg_status_o Bidir 32

